### ISSUE TITLE
SwinUNETR with SSL weights - possibly incorrect input data format

### ISSUE THREAD

**Issue by ibro45** [MIC-DKFZ/MultiTalent#7]
Hi, super interesting and useful work, thank you!

I was surprised to see basically no difference between from-scratch and SSL weights of the SwinUNETR org. implementation.  
<img width="881" alt="image" src="https://github.com/MIC-DKFZ/MultiTalent/assets/18015788/83818ba2-078f-4caa-ac17-14806a815dd5">

Did you ensure that the input format follows what SwinUNETR team used? As you can see from the screenshot of [SwinUNETR tutorial](https://github.com/Project-MONAI/tutorials/blob/main/3d_segmentation/swin_unetr_btcv_segmentation_3d.ipynb) below (look at where`slice_map[img_name]` is, as well as the plots), MONAI usually uses CXYZ, whereas I think you follow the PyTorch convention of CZYX judging by [this](https://github.com/MIC-DKFZ/MultiTalent/blob/21f21327119d23156f7dd3f16e262bcf0f739067/nnunet/training/network_training/nnUNet_variants/transformers/nnUNetTrainerV2_SwinUNETR_ddp.py#L127).

<img width="875" alt="image" src="https://github.com/MIC-DKFZ/MultiTalent/assets/18015788/5f466598-4c38-431b-af17-cf5f9ca8efb7">

If that's the case, the SSL weights would most likely provide no benefit, explaining the results in the table. However, I notice that ModelsGenesis doesn't provide any benefit either. I am pretty sure there would be no issues in the implementation of it considering the fact that they themselves used nnUNet for fine-tuning. It might just be the case that these (relatively small dataset) SSL pretrainings do not provide much value in decent-size multi-task datasets.

**Comment by constantinulrich** [comment]
Hi, we followed the Swinunetr tutorial that you mentioned (for the first two lines of the table).  For the next 3 lines, we used our own implementation within the nnU-Net framework and therefore had the  CZYX  convention that you found in the code :)
Note that you can't compare the Swinunetr BTCV results from the original paper, because they used some additional private data. 

For both the modelgenesis pretraining and the swinunetr pretraining we observed faster convergence but, unfortunately, now better final performance. And I totally agree that for SSL pretraining, we need much more data.  I am really looking forward to upcoming work in our field that actually demonstrates that SSL works for medical image segmentation.

One last addition: I have come to the conclusion that multi-organ segmentation is generally the wrong task to test pretraining methods, as we have already reached a certain saturation point. 

Best 
Constantin

**Comment by ibro45** [comment]
Hi Constantin,

Thank you for your answer! Really great to hear that, it gets so confusing with all the conventions, definitely had a few of those moments myself 😅

> One last addition: I have come to the conclusion that multi-organ segmentation is generally the wrong task to test pretraining methods, as we have already reached a certain saturation point.

I believe so too! Would be great to discuss that if we ever run into each other at a conference. Once again, really cool work, congrats, and good luck with publishing it in a nice journal/conference!
