### ISSUE TITLE
Missing Model Trainer for Pretrained Model

### ISSUE THREAD

**Issue by Awayah** [MIC-DKFZ/MultiTalent#8]
```
RuntimeError: Could not find the model trainer specified in checkpoint in nnunet.trainig.network_training. 
If it is not located there, please move it or change the code of restore_model. 
Your model trainer can be located in any directory within nnunet.trainig.network_training (search is recursive).
Debug info: 
checkpoint file: None
Name of trainer: nnUNetTrainerV2_leBFnnUNet4_regions_forceBD_DDP_customSplit_sqrtDSSampling_2000epochs
```

Problem Description:
When attempting to run a simple inference I got the error above.

I downloaded the pretrained model from here: https://zenodo.org/records/8297767/files/Task100_MultiTalent.zip?download=1

In the provided pkl files the specified architecture/ trainer for all folds and models is the `nnUNetTrainerV2_leBFnnUNet4_regions_forceBD_DDP_customSplit_sqrtDSSampling_2000epochs` 

However, in the entire repo I cannot find this architecture defined. This results in a runtime error, as the system cannot locate the necessary trainer class..

Please help me figure this out.

**Comment by constantinulrich** [comment]
Hi, please use the script, that i provided to download the files (I do some renaming of the files).
 

`nnUNet_download_pretrained_model Task100_MultiTalent`

**Comment by Awayah** [comment]
Thank you for your response. However, I have trouble downloading the zip file that way. 
When I use: `nnUNet_download_pretrained_model Task100_MultiTalent` I get this error and it beats me:

```
 raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://zenodo.org/record/8297767/files/Task100_MultiTalent.zip?download=1
```
I tried with different clients too, because I was unable to debug this, but have the same error
However, I can manually download from the link. 

If you can provide some guidance, or perhaps any instructions on how to do the renaming myself.

**Comment by constantinulrich** [comment]
Hi, 
okay i checked it and i had the same error. The issue seems to be that the HTTP version is set to 1.0 (default is 1.1), which was probably necessary for Zenodo at one point. There was an [update](https://help.zenodo.org/docs/about/whats-changed/) of Zenodo recently, where they probably changed that. 

Just delete [lines](https://github.com/MIC-DKFZ/MultiTalent/blob/21f21327119d23156f7dd3f16e262bcf0f739067/nnunet/inference/pretrained_models/download_pretrained_model.py#L301) 301-303 and it should work. I will update the code. 
However, below line 274 you would find all the necessary (manual) renamings...

Related to nnU-Net issue no. [1752](https://github.com/MIC-DKFZ/nnUNet/issues/1752) :)

Best, 
Constantin

**Comment by Awayah** [comment]
Thank you for the prompt help! I am able to verify that it works. 
I also see you updated the code, thanks!
